# Generated by Django 5.1.1 on 2024-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(max_length=300, verbose_name="descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "No iniciado"),
                            ("in_progress", "En progreso"),
                            ("completed", "Finalizado"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
            ],
        ),
    ]
