# Generated by Django 5.1.1 on 2024-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="fecha de actualización"
            ),
        ),
    ]
