# Generated by Django 5.1.1 on 2024-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tasks", "0003_tasks_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={"verbose_name": "Tarea", "verbose_name_plural": "Tareas"},
        ),
        migrations.AlterField(
            model_name="tasks",
            name="description",
            field=models.TextField(
                blank=True, max_length=300, verbose_name="descripción"
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="name",
            field=models.TextField(max_length=100, verbose_name="nombre"),
        ),
    ]
